# Generated by Django 4.2.3 on 2023-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano_aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoaula',
            name='dia_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
